---
# ansible/playbooks/03_prepare_standby.yml
- name: "Prepare Standby Server & Start NOMOUNT"
  hosts: standby
  gather_facts: yes
  become: yes
  become_user: "{{ standby.ssh_user | default('oracle') }}"
  vars:
    oh: "{{ standby.oracle_home }}"
    ob: "{{ standby.oracle_base | default('/u01/app/oracle') }}"
    sid: "{{ standby.sid }}"
    p_uniq: "{{ primary.db_unique_name }}"
    s_uniq: "{{ standby.db_unique_name }}"
    is_asm: "{{ standby.storage_type | default('asm') == 'asm' }}"
    is_cdb: "{{ primary.is_cdb | default(false) | bool }}"
    asm_data: "{{ standby.asm_dg_data | default('+DATA') }}"
    asm_fra: "{{ standby.asm_dg_fra | default('+FRA') }}"
    data_dir: "{{ standby.data_dir | default('') }}"
    fra_dir: "{{ standby.fra_dir | default('') }}"

  tasks:

    # ── Create Directories (Filesystem) ────────────────────────────────────
    - name: Create filesystem directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ standby.ssh_user | default('oracle') }}"
        mode: '0755'
      loop:
        - "{{ ob }}/admin/{{ sid }}/adump"
        - "{{ ob }}/admin/{{ sid }}/dpdump"
        - "{{ ob }}/admin/{{ sid }}/pfile"
        - "{{ oh }}/dbs"
      loop_control:
        label: "{{ item }}"

    - name: Create data/fra directories (filesystem only)
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ standby.ssh_user | default('oracle') }}"
        mode: '0755'
      loop:
        - "{{ data_dir }}"
        - "{{ fra_dir }}"
      when:
        - not is_asm | bool
        - item | length > 0

    # ── Generate init.ora ──────────────────────────────────────────────────
    - name: Create standby init.ora (ASM)
      copy:
        dest: "{{ oh }}/dbs/init{{ sid }}.ora"
        content: |
          # Standby init.ora - generated by automation
          db_name='{{ primary.sid }}'
          db_unique_name='{{ s_uniq }}'
          db_block_size=8192
          compatible='{{ primary.oracle_version | default("19.0.0") }}'
          {% if is_asm | bool %}
          db_create_file_dest='{{ asm_data }}'
          db_recovery_file_dest='{{ asm_fra }}'
          db_recovery_file_dest_size=100G
          {% else %}
          db_create_file_dest='{{ data_dir }}'
          db_recovery_file_dest='{{ fra_dir if fra_dir else data_dir + "/fra" }}'
          db_recovery_file_dest_size=100G
          {% endif %}
          control_files='{% if is_asm | bool %}{{ asm_data }}/{{ s_uniq }}/controlfile/control01.ctl','{{ asm_fra }}/{{ s_uniq }}/controlfile/control02.ctl{% else %}{{ data_dir }}/control01.ctl','{{ data_dir }}/control02.ctl{% endif %}'
          log_archive_config='DG_CONFIG=({{ p_uniq }},{{ s_uniq }})'
          log_archive_dest_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME={{ s_uniq }}'
          log_archive_dest_2='SERVICE={{ p_uniq }} ASYNC VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME={{ p_uniq }}'
          fal_server='{{ p_uniq }}'
          remote_login_passwordfile='EXCLUSIVE'
          audit_file_dest='{{ ob }}/admin/{{ sid }}/adump'
          diagnostic_dest='{{ ob }}'
          standby_file_management='AUTO'
          {% if rman.db_file_name_convert | default('') | length > 0 %}
          db_file_name_convert={{ rman.db_file_name_convert }}
          log_file_name_convert={{ rman.log_file_name_convert | default(rman.db_file_name_convert) }}
          {% endif %}
          {% if is_cdb | bool %}
          enable_pluggable_database=TRUE
          {% endif %}
        owner: "{{ standby.ssh_user | default('oracle') }}"
        mode: '0644'

    # ── Password File ──────────────────────────────────────────────────────
    - name: Copy password file from Ansible control node
      copy:
        src: "/tmp/orapw{{ standby.sid }}"
        dest: "{{ oh }}/dbs/orapw{{ sid }}"
        owner: "{{ standby.ssh_user | default('oracle') }}"
        mode: '0640'
      ignore_errors: yes

    - name: Create password file if copy failed
      shell: |
        export ORACLE_HOME={{ oh }} PATH={{ oh }}/bin:$PATH
        orapwd file={{ oh }}/dbs/orapw{{ sid }} password={{ oracle_sys_password }} entries=10 force=y
      when: false  # Set to true if copy above fails
      ignore_errors: yes

    # ── TNS Configuration ──────────────────────────────────────────────────
    - name: Configure tnsnames.ora on standby
      copy:
        dest: "{{ oh }}/network/admin/tnsnames.ora"
        content: |
          # Generated by Oracle Standby Automation

          {{ p_uniq }} =
            (DESCRIPTION =
              (ADDRESS = (PROTOCOL = TCP)(HOST = {{ primary.host }})(PORT = {{ primary.listener_port | default(1521) }}))
              (CONNECT_DATA =
                (SERVER = DEDICATED)
                (SERVICE_NAME = {{ p_uniq }})))

          {{ s_uniq }} =
            (DESCRIPTION =
              (ADDRESS = (PROTOCOL = TCP)(HOST = {{ standby.host }})(PORT = {{ standby.listener_port | default(1521) }}))
              (CONNECT_DATA =
                (SERVER = DEDICATED)
                (SERVICE_NAME = {{ s_uniq }})))
        owner: "{{ standby.ssh_user | default('oracle') }}"
        mode: '0644'

    # ── Static Listener Registration ───────────────────────────────────────
    - name: Add static listener entry for standby
      blockinfile:
        path: "{{ oh }}/network/admin/listener.ora"
        create: yes
        marker: "# {mark} STANDBY STATIC REGISTRATION"
        block: |
          SID_LIST_LISTENER =
            (SID_LIST =
              (SID_DESC =
                (GLOBAL_DBNAME = {{ s_uniq }})
                (ORACLE_HOME = {{ oh }})
                (SID_NAME = {{ sid }}))
              (SID_DESC =
                (GLOBAL_DBNAME = {{ s_uniq }}_DGMGRL)
                (ORACLE_HOME = {{ oh }})
                (SID_NAME = {{ sid }})))
        owner: "{{ standby.ssh_user | default('oracle') }}"
        mode: '0644'

    - name: Reload listener
      shell: |
        export ORACLE_HOME={{ oh }} PATH={{ oh }}/bin:$PATH
        lsnrctl reload
      ignore_errors: yes

    # ── Start Instance NOMOUNT ─────────────────────────────────────────────
    - name: Check if instance already running
      shell: |
        export ORACLE_HOME={{ oh }} ORACLE_SID={{ sid }} PATH={{ oh }}/bin:$PATH
        echo "SELECT STATUS FROM V\$INSTANCE;" | sqlplus -s / as sysdba 2>/dev/null | grep -i 'started\|mounted\|open' || true
      register: inst_check
      changed_when: false

    - name: Shutdown if running in wrong state
      shell: |
        export ORACLE_HOME={{ oh }} ORACLE_SID={{ sid }} PATH={{ oh }}/bin:$PATH
        sqlplus -s / as sysdba <<< "SHUTDOWN ABORT;"
      when: inst_check.stdout | length > 0
      ignore_errors: yes

    - name: Start standby instance NOMOUNT
      shell: |
        export ORACLE_HOME={{ oh }} ORACLE_SID={{ sid }} PATH={{ oh }}/bin:$PATH
        sqlplus -s / as sysdba <<SQL
        STARTUP NOMOUNT PFILE='{{ oh }}/dbs/init{{ sid }}.ora';
        SQL
      register: nomount
      failed_when: "'STARTED' not in nomount.stdout and 'already started' not in nomount.stdout | lower"

    - name: Verify NOMOUNT state
      shell: |
        export ORACLE_HOME={{ oh }} ORACLE_SID={{ sid }} PATH={{ oh }}/bin:$PATH
        echo "SELECT STATUS FROM V\$INSTANCE;" | sqlplus -s / as sysdba
      register: verify_nomount
      changed_when: false
      failed_when: "'STARTED' not in verify_nomount.stdout"

    - name: Test TNS to primary
      shell: |
        export ORACLE_HOME={{ oh }} PATH={{ oh }}/bin:$PATH
        tnsping {{ p_uniq }}
      register: tns_test
      changed_when: false
      failed_when: tns_test.rc != 0
